version: '3.9'

services:
  db:
    image: postgres:16
    container_name: onlineexam-postgres
    environment:
      POSTGRES_DB: onlineexam
      POSTGRES_USER: onlineexam
      POSTGRES_PASSWORD: onlineexam
    ports:
      - "5432:5432"
    volumes:
      - onlineexam_db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/OnlineExam.Api/Dockerfile
    container_name: onlineexam-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5045
      # KËTU duhet connection string i DB brenda docker network
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=onlineexam;Username=onlineexam;Password=onlineexam
    ports:
      - "5045:5045"

volumes:
  onlineexam_db: