// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineExam.Api.Data;

#nullable disable

namespace OnlineExam.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403073935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineExam.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0f054d5-d476-40d7-b57f-727165dc0e18"),
                            CreatedAt = new DateTime(2026, 4, 3, 7, 39, 33, 56, DateTimeKind.Utc).AddTicks(3240),
                            Email = "admin@onlineexam.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("17ef169c-c82d-44e3-8d24-e1fdc6ecf3be"),
                            CreatedAt = new DateTime(2026, 4, 3, 7, 39, 33, 56, DateTimeKind.Utc).AddTicks(3244),
                            Email = "prof@onlineexam.com",
                            FullName = "Professor",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = new Guid("ea3f5ee5-638d-416c-9ef9-3f614007342e"),
                            CreatedAt = new DateTime(2026, 4, 3, 7, 39, 33, 56, DateTimeKind.Utc).AddTicks(3246),
                            Email = "student@onlineexam.com",
                            FullName = "Student",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
