// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineExam.Api.Data;

#nullable disable

namespace OnlineExam.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409204120_RemoveShadowExamId1")]
    partial class RemoveShadowExamId1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineExam.Api.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("OnlineExam.Api.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnlineExam.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b17cb2e7-24c3-43ef-8cbe-9cadd3d05fc4"),
                            CreatedAt = new DateTime(2026, 4, 9, 20, 41, 20, 30, DateTimeKind.Utc).AddTicks(4655),
                            Email = "admin@onlineexam.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("72f91bcd-254b-4dfc-98cc-9dece7506cb8"),
                            CreatedAt = new DateTime(2026, 4, 9, 20, 41, 20, 30, DateTimeKind.Utc).AddTicks(4661),
                            Email = "prof@onlineexam.com",
                            FullName = "Professor",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = new Guid("be5dc142-5672-481e-92bd-7ac772db21a1"),
                            CreatedAt = new DateTime(2026, 4, 9, 20, 41, 20, 30, DateTimeKind.Utc).AddTicks(4665),
                            Email = "student@onlineexam.com",
                            FullName = "Student",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("OnlineExam.Api.Models.Question", b =>
                {
                    b.HasOne("OnlineExam.Api.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("OnlineExam.Api.Models.Exam", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
